[package]
cairo-version = "2.13.1"
name = "pixelaw_test_utils"
version = "0.7.9"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
pixelaw = { path = "../contracts" }
dojo = "1.8.0"
starknet = "2.13.1"
dojo_cairo_test = "1.8.0"

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[lib]
