[package]
cairo-version = "2.12.2"
name = "pixelaw_test_utils"
version = "0.7.9"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
pixelaw = { path = "../contracts" }
dojo = "1.7.1"
starknet = "2.12.2"
dojo_cairo_test = "1.7.1"

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[lib]
