kind = "DojoModel"
class_hash = "0x71570f33b7f66331952b84691bb5794ee6b19f43ad729cc654c3930f47c5f0d"
original_class_hash = "0x71570f33b7f66331952b84691bb5794ee6b19f43ad729cc654c3930f47c5f0d"
abi = "manifests/dev-pop/base/abis/models/pixelaw-Pixel-7e607b2f.json"
tag = "pixelaw-Pixel"
qualified_path = "pixelaw::core::models::pixel::pixel"
manifest_name = "pixelaw-Pixel-7e607b2f"

[[members]]
name = "x"
type = "u32"
key = true

[[members]]
name = "y"
type = "u32"
key = true

[[members]]
name = "app"
type = "ContractAddress"
key = false

[[members]]
name = "color"
type = "u32"
key = false

[[members]]
name = "created_at"
type = "u64"
key = false

[[members]]
name = "updated_at"
type = "u64"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "text"
type = "felt252"
key = false

[[members]]
name = "action"
type = "felt252"
key = false
