kind = "DojoModel"
class_hash = "0x615da1d9db8eef7b84db6c92211fd202646d12de041b3e6ea6f3a7abec73e49"
original_class_hash = "0x615da1d9db8eef7b84db6c92211fd202646d12de041b3e6ea6f3a7abec73e49"
abi = "manifests/dev-pop/base/abis/models/pixelaw-RTree-3baaf9fe.json"
tag = "pixelaw-RTree"
qualified_path = "pixelaw::core::models::area::r_tree"
manifest_name = "pixelaw-RTree-3baaf9fe"

[[members]]
name = "id"
type = "u64"
key = true

[[members]]
name = "children"
type = "felt252"
key = false
