kind = "DojoModel"
class_hash = "0x5a3afeed7a51a51cab27a99c9d99064fc467ecdb9a8cc606c4d4899dffb7f6c"
original_class_hash = "0x5a3afeed7a51a51cab27a99c9d99064fc467ecdb9a8cc606c4d4899dffb7f6c"
abi = "manifests/sepolia/base/abis/models/pixelaw-Snake-62b876d4.json"
tag = "pixelaw-Snake"
qualified_path = "pixelaw::apps::snake::app::snake"
manifest_name = "pixelaw-Snake-62b876d4"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "length"
type = "u8"
key = false

[[members]]
name = "first_segment_id"
type = "u32"
key = false

[[members]]
name = "last_segment_id"
type = "u32"
key = false

[[members]]
name = "direction"
type = "Direction"
key = false

[[members]]
name = "color"
type = "u32"
key = false

[[members]]
name = "text"
type = "felt252"
key = false

[[members]]
name = "is_dying"
type = "bool"
key = false
