kind = "DojoModel"
class_hash = "0x296cfe5fb82a8b03b4aa78e35955bc70971babeb414d70a6a8acc52a4eacab2"
original_class_hash = "0x296cfe5fb82a8b03b4aa78e35955bc70971babeb414d70a6a8acc52a4eacab2"
abi = "manifests/sepolia/base/abis/models/pixelaw-CoreActionsAddress-5379e1ce.json"
tag = "pixelaw-CoreActionsAddress"
qualified_path = "pixelaw::core::models::registry::core_actions_address"
manifest_name = "pixelaw-CoreActionsAddress-5379e1ce"

[[members]]
name = "key"
type = "felt252"
key = true

[[members]]
name = "value"
type = "ContractAddress"
key = false
