kind = "DojoModel"
class_hash = "0x672114a91934388e6a4950f164dc151894579281f4eab56fe439108fd4fca70"
original_class_hash = "0x672114a91934388e6a4950f164dc151894579281f4eab56fe439108fd4fca70"
abi = "manifests/sepolia/base/abis/models/pixelaw-QueueItem-549a17f2.json"
tag = "pixelaw-QueueItem"
qualified_path = "pixelaw::core::models::queue::queue_item"
manifest_name = "pixelaw-QueueItem-549a17f2"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "valid"
type = "bool"
key = false
