kind = "DojoModel"
class_hash = "0x4a51f0c4ffde38ee62c5edda4b8ac89892063623f6cbc0eeadbfb271cac83ae"
original_class_hash = "0x4a51f0c4ffde38ee62c5edda4b8ac89892063623f6cbc0eeadbfb271cac83ae"
abi = "manifests/dev/base/abis/models/pixelaw-Area-41f22f17.json"
tag = "pixelaw-Area"
qualified_path = "pixelaw::core::models::area::area"
manifest_name = "pixelaw-Area-41f22f17"

[[members]]
name = "id"
type = "u64"
key = true

[[members]]
name = "app"
type = "ContractAddress"
key = false

[[members]]
name = "owner"
type = "ContractAddress"
key = false

[[members]]
name = "color"
type = "u32"
key = false
